name: 'Changelog Generator from tags'
description: 'Creates or replace a changelog file in your repository'
branding:
  icon: file-text
  color: red
inputs:
  previous-tag:
    description: 'Changelog will start after specified tag.'
    required: true
  current-tag:
    description: 'Changelog will end before specified tag.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.previous-tag }}
    - ${{ inputs.current-tag }}